package com.qcwireless.qcwatch.base.pref;

/* compiled from: UserConfigDAO.kt */
@kotlin.Metadata(d1 = {"\u0000\"\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010\u000e\n\u0002\bL\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\bÆ\u0002\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002J\u000e\u0010P\u001a\u00020Q2\u0006\u0010R\u001a\u00020SJ\u000e\u0010T\u001a\u00020Q2\u0006\u0010R\u001a\u00020SJ\u000e\u0010U\u001a\u00020Q2\u0006\u0010R\u001a\u00020SR\u000e\u0010\u0003\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0005\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0006\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0007\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\b\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\t\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\n\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u000b\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\f\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\r\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u000e\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u000f\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0010\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0011\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0012\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0013\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0014\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0015\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0016\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0017\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0018\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0019\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u001a\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u001b\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u001c\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u001d\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u001e\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u001f\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010 \u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010!\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\"\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010#\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010$\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010%\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010&\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010'\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010(\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010)\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010*\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010+\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010,\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010-\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010.\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010/\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00100\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00101\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00102\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00103\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00104\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00105\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00106\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00107\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00108\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u00109\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010:\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010;\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010<\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010=\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010>\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010?\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010@\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010A\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010B\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010C\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010D\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010E\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010F\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010G\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010H\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010I\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010J\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010K\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010L\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010M\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010N\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010O\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000¨\u0006V"}, d2 = {"Lcom/qcwireless/qcwatch/base/pref/UserConfigDAO;", "", "()V", "Action_Action_Ebook", "", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_AlbumSupport, "Action_BloodSugarSupport", "Action_Call_Push", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_China_App, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Classic_Bluetooth_Mac, "Action_Debug", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_DeviceActionList, "Action_Device_Address", "Action_Device_Address_No_Clear", "Action_Device_Name", "Action_Device_Name_No_Clear", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_GPSSupport, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_GoogleFit, "Action_GpsLocationTime", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Gps_Warming, "Action_HealthyModel", "Action_Hw_version", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_IndexApiUpdateTme, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_JieLiMusic, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Language_Curr, "Action_LastLocation", "Action_Last_Device", "Action_Login_Status", "Action_LyricsSupport", "Action_ManualDND", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_MaxContacts, "Action_MenstruationSetting", "Action_MessagePush", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_MessagePushDeviceSupport, "Action_Metric", "Action_MusicSupport", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_OneKeySupport, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Permission_Desc, "Action_RtkMcuSupport", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Skin_Curr, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Skus, "Action_Sms_Push", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_SupportContact, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Support_WeChat, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_Travel_Mode, "Action_UID", "Action_UserEmail", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_UserPhotoAction, "Action_UserPwd", "Action_UserToken", "Action_WakeUp_Time", "Action_WatchFaceApiFlag", "Action_Weather_Info", "Action_Weather_LastTime", "Action_Weather_ToDevice_LastTime", "Action_battery", "Action_devTest", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_deviceAvatarSupport, "Action_deviceBatteryLow", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_firstUser, "Action_fm_version", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_google_fit_last_info, "Action_gpsPermission", com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_heartRateIntervalSupport, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_lastCollectionTime, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_lastSyncFromServerTime, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_lastSyncTodaySteps, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_lastTenMinSyncTime, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_maxWatchFace, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_newSleepProtocol, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_otherSoftwarePush, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_serverMarketSize, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_temperature, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_warmingAutoStart, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_warmingBatteryAllow, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_warmingBatteryWhite, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_warmingLockApp, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_warmingNotification, com.qcwireless.qcwatch.base.pref.UserConfigDAO.Action_watchFaceMarketVersion, "PREFERENCE_FILE_NAME", "clear", "", "userConfig", "Lcom/qcwireless/qcwatch/base/pref/UserConfig;", "readUserConfig", "saveUserConfig", "app_championRelease"}, k = 1, mv = {1, 6, 0}, xi = 48)
/* loaded from: /tmp/dex/classes2.dex */
public final class UserConfigDAO {
    private static final java.lang.String Action_Action_Ebook = "Action_Ebook";
    private static final java.lang.String Action_AlbumSupport = "Action_AlbumSupport";
    private static final java.lang.String Action_BloodSugarSupport = "Action_bloodSugarSupport";
    private static final java.lang.String Action_Call_Push = "com.qc.Action_Call_Push";
    private static final java.lang.String Action_China_App = "Action_China_App";
    private static final java.lang.String Action_Classic_Bluetooth_Mac = "Action_Classic_Bluetooth_Mac";
    private static final java.lang.String Action_Debug = "com.qc.Action_Debug";
    private static final java.lang.String Action_DeviceActionList = "Action_DeviceActionList";
    private static final java.lang.String Action_Device_Address = "com.qc.Action_Device_Address";
    private static final java.lang.String Action_Device_Address_No_Clear = "com.qc.Action_Device_Address_No_Clear";
    private static final java.lang.String Action_Device_Name = "com.qc.Action_DeviceName";
    private static final java.lang.String Action_Device_Name_No_Clear = "com.qc.Action_DeviceName_No_Clear";
    private static final java.lang.String Action_GPSSupport = "Action_GPSSupport";
    private static final java.lang.String Action_GoogleFit = "Action_GoogleFit";
    private static final java.lang.String Action_GpsLocationTime = "Action_gpsLocationTime";
    private static final java.lang.String Action_Gps_Warming = "Action_Gps_Warming";
    private static final java.lang.String Action_HealthyModel = "com.qc.Action_HealthyModel";
    private static final java.lang.String Action_Hw_version = "com.qc.Action_Hw_version";
    private static final java.lang.String Action_IndexApiUpdateTme = "Action_IndexApiUpdateTme";
    private static final java.lang.String Action_JieLiMusic = "Action_JieLiMusic";
    private static final java.lang.String Action_Language_Curr = "Action_Language_Curr";
    private static final java.lang.String Action_LastLocation = "Action_lastLocationTime";
    private static final java.lang.String Action_Last_Device = "com.qc.Action_last_device_address";
    private static final java.lang.String Action_Login_Status = "com.qc.Action_Login_Status";
    private static final java.lang.String Action_LyricsSupport = "Action_lyricsSupport";
    private static final java.lang.String Action_ManualDND = "Action_manualDND";
    private static final java.lang.String Action_MaxContacts = "Action_MaxContacts";
    private static final java.lang.String Action_MenstruationSetting = "com.qc.menstruationSetting";
    private static final java.lang.String Action_MessagePush = "com.qc.messagePushEnable";
    private static final java.lang.String Action_MessagePushDeviceSupport = "Action_MessagePushDeviceSupport";
    private static final java.lang.String Action_Metric = "com.qc.metric";
    private static final java.lang.String Action_MusicSupport = "Action_musicSupport";
    private static final java.lang.String Action_OneKeySupport = "Action_OneKeySupport";
    private static final java.lang.String Action_Permission_Desc = "Action_Permission_Desc";
    private static final java.lang.String Action_RtkMcuSupport = "Action_rtkMcuSupport";
    private static final java.lang.String Action_Skin_Curr = "Action_Skin_Curr";
    private static final java.lang.String Action_Skus = "Action_Skus";
    private static final java.lang.String Action_Sms_Push = "com.qc.Action_Sms_Push";
    private static final java.lang.String Action_SupportContact = "Action_SupportContact";
    private static final java.lang.String Action_Support_WeChat = "Action_Support_WeChat";
    private static final java.lang.String Action_Travel_Mode = "Action_Travel_Mode";
    private static final java.lang.String Action_UID = "com.qc.uid";
    private static final java.lang.String Action_UserEmail = "com.qc.userEmail";
    private static final java.lang.String Action_UserPhotoAction = "Action_UserPhotoAction";
    private static final java.lang.String Action_UserPwd = "com.qc.UserPwd";
    private static final java.lang.String Action_UserToken = "com.qc.userToken";
    private static final java.lang.String Action_WakeUp_Time = "com.qc.WakeUp_Time";
    private static final java.lang.String Action_WatchFaceApiFlag = "Action_watchFaceApiFlag";
    private static final java.lang.String Action_Weather_Info = "com.qc.weatherInfo";
    private static final java.lang.String Action_Weather_LastTime = "com.qc.weather_last_time";
    private static final java.lang.String Action_Weather_ToDevice_LastTime = "com.qc.Action_Weather_ToDevice_LastTime";
    private static final java.lang.String Action_battery = "com.qc.Action_battery";
    private static final java.lang.String Action_devTest = "Action_devTest_development";
    private static final java.lang.String Action_deviceAvatarSupport = "Action_deviceAvatarSupport";
    private static final java.lang.String Action_deviceBatteryLow = "Action_batteryLow";
    private static final java.lang.String Action_firstUser = "Action_firstUser";
    private static final java.lang.String Action_fm_version = "com.qc.Action_fm_version";
    private static final java.lang.String Action_google_fit_last_info = "Action_google_fit_last_info";
    private static final java.lang.String Action_gpsPermission = "Action_Action_gpsPermission";
    private static final java.lang.String Action_heartRateIntervalSupport = "Action_heartRateIntervalSupport";
    private static final java.lang.String Action_lastCollectionTime = "Action_lastCollectionTime";
    private static final java.lang.String Action_lastSyncFromServerTime = "Action_lastSyncFromServerTime";
    private static final java.lang.String Action_lastSyncTodaySteps = "Action_lastSyncTodaySteps";
    private static final java.lang.String Action_lastTenMinSyncTime = "Action_lastTenMinSyncTime";
    private static final java.lang.String Action_maxWatchFace = "Action_maxWatchFace";
    private static final java.lang.String Action_newSleepProtocol = "Action_newSleepProtocol";
    private static final java.lang.String Action_otherSoftwarePush = "Action_otherSoftwarePush";
    private static final java.lang.String Action_serverMarketSize = "Action_serverMarketSize";
    private static final java.lang.String Action_temperature = "Action_temperature";
    private static final java.lang.String Action_warmingAutoStart = "Action_warmingAutoStart";
    private static final java.lang.String Action_warmingBatteryAllow = "Action_warmingBatteryAllow";
    private static final java.lang.String Action_warmingBatteryWhite = "Action_warmingBatteryWhite";
    private static final java.lang.String Action_warmingLockApp = "Action_warmingLockApp";
    private static final java.lang.String Action_warmingNotification = "Action_warmingNotification";
    private static final java.lang.String Action_watchFaceMarketVersion = "Action_watchFaceMarketVersion";
    public static final com.qcwireless.qcwatch.base.pref.UserConfigDAO INSTANCE = new com.qcwireless.qcwatch.base.pref.UserConfigDAO();
    private static final java.lang.String PREFERENCE_FILE_NAME = "UserConfig_Preferences_Qc_1.0";

    private UserConfigDAO() {
    }

    public final void readUserConfig(com.qcwireless.qcwatch.base.pref.UserConfig userConfig) {
        kotlin.jvm.internal.Intrinsics.checkNotNullParameter(userConfig, "userConfig");
        android.content.SharedPreferences sharedPreferences = com.qcwireless.qcwatch.base.pref.PreUtil.getSharedPreferences(PREFERENCE_FILE_NAME, userConfig.getContext());
        userConfig.setDebug(sharedPreferences.getBoolean(Action_Debug, userConfig.getIsDebug()));
        userConfig.setDeviceName(java.lang.String.valueOf(sharedPreferences.getString("com.qc.Action_DeviceName", userConfig.getDeviceName())));
        userConfig.setDeviceAddress(java.lang.String.valueOf(sharedPreferences.getString("com.qc.Action_Device_Address", userConfig.getDeviceAddress())));
        userConfig.setHwVersion(java.lang.String.valueOf(sharedPreferences.getString(Action_Hw_version, userConfig.getHwVersion())));
        userConfig.setFmVersion(java.lang.String.valueOf(sharedPreferences.getString(Action_fm_version, userConfig.getFmVersion())));
        userConfig.setBattery(sharedPreferences.getString(Action_battery, userConfig.getBattery()));
        userConfig.setLastDeviceAddress(sharedPreferences.getString(Action_Last_Device, userConfig.getLastDeviceAddress()));
        userConfig.setHealthyModel(sharedPreferences.getString(Action_HealthyModel, userConfig.getHealthyModel()));
        userConfig.setDeviceNameNoClear(java.lang.String.valueOf(sharedPreferences.getString(Action_Device_Name_No_Clear, userConfig.getDeviceNameNoClear())));
        userConfig.setDeviceAddressNoClear(java.lang.String.valueOf(sharedPreferences.getString(Action_Device_Address_No_Clear, userConfig.getDeviceAddressNoClear())));
        userConfig.setLoginStatus(sharedPreferences.getBoolean(Action_Login_Status, userConfig.getLoginStatus()));
        userConfig.setUserToken(java.lang.String.valueOf(sharedPreferences.getString(Action_UserToken, userConfig.getUserToken())));
        userConfig.setUserEmail(java.lang.String.valueOf(sharedPreferences.getString(Action_UserEmail, userConfig.getUserEmail())));
        userConfig.setUserPwd(java.lang.String.valueOf(sharedPreferences.getString(Action_UserPwd, userConfig.getUserPwd())));
        userConfig.setUid(sharedPreferences.getLong(Action_UID, userConfig.getUid()));
        userConfig.setMetric(sharedPreferences.getBoolean(Action_Metric, userConfig.getMetric()));
        userConfig.setMenstruationSetting(sharedPreferences.getBoolean(Action_MenstruationSetting, userConfig.getMenstruationSetting()));
        userConfig.setCallPushEnable(sharedPreferences.getBoolean(Action_Call_Push, userConfig.getCallPushEnable()));
        userConfig.setSmsPushEnable(sharedPreferences.getBoolean(Action_Sms_Push, userConfig.getSmsPushEnable()));
        userConfig.setWakeTime(sharedPreferences.getLong(Action_WakeUp_Time, userConfig.getWakeTime()));
        userConfig.setMessagePushEnable(sharedPreferences.getBoolean(Action_MessagePush, userConfig.getMessagePushEnable()));
        userConfig.setWeatherLastTime(sharedPreferences.getInt(Action_Weather_LastTime, userConfig.getWeatherLastTime()));
        userConfig.setWeatherToDeviceLastTime(sharedPreferences.getInt(Action_Weather_ToDevice_LastTime, userConfig.getWeatherToDeviceLastTime()));
        userConfig.setWeatherInfo(java.lang.String.valueOf(sharedPreferences.getString(Action_Weather_Info, userConfig.getWeatherInfo())));
        userConfig.setPermissionDescFlag(sharedPreferences.getBoolean(Action_Permission_Desc, userConfig.getPermissionDescFlag()));
        userConfig.setGpsWarmingDialog(sharedPreferences.getBoolean(Action_Gps_Warming, userConfig.getGpsWarmingDialog()));
        userConfig.setLanguageCurr(java.lang.String.valueOf(sharedPreferences.getString(Action_Language_Curr, userConfig.getLanguageCurr())));
        userConfig.setSkinType(sharedPreferences.getInt(Action_Skin_Curr, userConfig.getSkinType()));
        userConfig.setLastSyncFromServerTime(sharedPreferences.getLong(Action_lastSyncFromServerTime, userConfig.getLastSyncFromServerTime()));
        userConfig.setOneKeySupport(java.lang.String.valueOf(sharedPreferences.getString(Action_OneKeySupport, userConfig.getOneKeySupport())));
        userConfig.setFirstUse(sharedPreferences.getBoolean(Action_firstUser, userConfig.getFirstUse()));
        userConfig.setLastSyncTodaySteps(sharedPreferences.getLong(Action_lastSyncTodaySteps, userConfig.getLastSyncTodaySteps()));
        userConfig.setWatchFaceMarketVersion(sharedPreferences.getLong(Action_watchFaceMarketVersion, userConfig.getWatchFaceMarketVersion()));
        userConfig.setLastCollectionTime(sharedPreferences.getLong(Action_lastCollectionTime, userConfig.getLastCollectionTime()));
        userConfig.setGpsPermission(sharedPreferences.getLong(Action_gpsPermission, userConfig.getGpsPermission()));
        userConfig.setWarmingNotification(sharedPreferences.getBoolean(Action_warmingNotification, userConfig.getWarmingNotification()));
        userConfig.setWarmingBatteryWhite(sharedPreferences.getBoolean(Action_warmingBatteryWhite, userConfig.getWarmingBatteryWhite()));
        userConfig.setWarmingAutoStart(sharedPreferences.getBoolean(Action_warmingAutoStart, userConfig.getWarmingAutoStart()));
        userConfig.setWarmingLock(sharedPreferences.getBoolean(Action_warmingLockApp, userConfig.getWarmingLock()));
        userConfig.setWarmingBatteryAllow(sharedPreferences.getBoolean(Action_warmingBatteryAllow, userConfig.getWarmingBatteryAllow()));
        userConfig.setLastUserPhotoModifyTime(sharedPreferences.getLong(Action_UserPhotoAction, userConfig.getLastUserPhotoModifyTime()));
        userConfig.setGoogleFit(sharedPreferences.getBoolean(Action_GoogleFit, userConfig.getGoogleFit()));
        userConfig.setNewSleepProtocol(sharedPreferences.getBoolean(Action_newSleepProtocol, userConfig.getNewSleepProtocol()));
        userConfig.setTemperature(sharedPreferences.getBoolean(Action_temperature, userConfig.getTemperature()));
        userConfig.setGoogleFitLastInfo(java.lang.String.valueOf(sharedPreferences.getString(Action_google_fit_last_info, userConfig.getGoogleFitLastInfo())));
        userConfig.setMaxWatchFace(sharedPreferences.getInt(Action_maxWatchFace, userConfig.getMaxWatchFace()));
        userConfig.setOtherSoftwarePush(sharedPreferences.getBoolean(Action_otherSoftwarePush, userConfig.getOtherSoftwarePush()));
        userConfig.setSupportContact(sharedPreferences.getBoolean(Action_SupportContact, userConfig.getSupportContact()));
        userConfig.setLastTenMinSyncTime(sharedPreferences.getLong(Action_lastTenMinSyncTime, userConfig.getLastTenMinSyncTime()));
        userConfig.setServerMarketSize(sharedPreferences.getInt(Action_serverMarketSize, userConfig.getServerMarketSize()));
        userConfig.setClassicBluetoothMac(java.lang.String.valueOf(sharedPreferences.getString(Action_Classic_Bluetooth_Mac, userConfig.getClassicBluetoothMac())));
        userConfig.setDeviceFunctionList(java.lang.String.valueOf(sharedPreferences.getString(Action_DeviceActionList, userConfig.getDeviceFunctionList())));
        userConfig.setIndexApiUpdateTime(sharedPreferences.getInt(Action_IndexApiUpdateTme, userConfig.getIndexApiUpdateTime()));
        userConfig.setSkusGoogle(java.lang.String.valueOf(sharedPreferences.getString(Action_Skus, userConfig.getSkusGoogle())));
        userConfig.setLastLocationTime(sharedPreferences.getInt(Action_LastLocation, userConfig.getLastLocationTime()));
        userConfig.setMaxContacts(sharedPreferences.getInt(Action_MaxContacts, userConfig.getMaxContacts()));
        userConfig.setWatchFaceApiFlag(sharedPreferences.getBoolean(Action_WatchFaceApiFlag, userConfig.getWatchFaceApiFlag()));
        userConfig.setMusicSupport(sharedPreferences.getBoolean(Action_MusicSupport, userConfig.getMusicSupport()));
        userConfig.setRtkMcuSupport(sharedPreferences.getBoolean(Action_RtkMcuSupport, userConfig.getRtkMcuSupport()));
        userConfig.setEbookSupport(sharedPreferences.getBoolean(Action_Action_Ebook, userConfig.getEbookSupport()));
        userConfig.setWechatSupport(sharedPreferences.getBoolean(Action_Support_WeChat, userConfig.getWechatSupport()));
        userConfig.setChinaApp(sharedPreferences.getBoolean(Action_China_App, userConfig.getChinaApp()));
        userConfig.setManualDND(sharedPreferences.getBoolean(Action_ManualDND, userConfig.getManualDND()));
        userConfig.setDevelopment(sharedPreferences.getBoolean(Action_devTest, userConfig.getDevelopment()));
        userConfig.setBloodSugarSupport(sharedPreferences.getBoolean(Action_BloodSugarSupport, userConfig.getBloodSugarSupport()));
        userConfig.setLyricsSupport(sharedPreferences.getBoolean(Action_LyricsSupport, userConfig.getLyricsSupport()));
        userConfig.setAlbumSupport(sharedPreferences.getBoolean(Action_AlbumSupport, userConfig.getAlbumSupport()));
        userConfig.setGpsSupport(sharedPreferences.getBoolean(Action_GPSSupport, userConfig.getGpsSupport()));
        userConfig.setTravelModel(sharedPreferences.getInt(Action_Travel_Mode, userConfig.getTravelModel()));
        userConfig.setJieLiMusic(sharedPreferences.getBoolean(Action_JieLiMusic, userConfig.getJieLiMusic()));
        userConfig.setGpsLocationTime(sharedPreferences.getLong(Action_GpsLocationTime, userConfig.getGpsLocationTime()));
        userConfig.setMessagePushSupport(sharedPreferences.getInt(Action_MessagePushDeviceSupport, userConfig.getMessagePushSupport()));
        userConfig.setDeviceAvatarSupport(sharedPreferences.getBoolean(Action_deviceAvatarSupport, userConfig.getDeviceAvatarSupport()));
        userConfig.setBatteryLow(sharedPreferences.getBoolean(Action_deviceBatteryLow, userConfig.getBatteryLow()));
        userConfig.setHeartRateInterval(sharedPreferences.getBoolean(Action_heartRateIntervalSupport, userConfig.getHeartRateInterval()));
    }

    public final void saveUserConfig(com.qcwireless.qcwatch.base.pref.UserConfig userConfig) {
        kotlin.jvm.internal.Intrinsics.checkNotNullParameter(userConfig, "userConfig");
        android.content.SharedPreferences.Editor sharedEditor = com.qcwireless.qcwatch.base.pref.PreUtil.getSharedEditor(PREFERENCE_FILE_NAME, userConfig.getContext());
        sharedEditor.putBoolean(Action_Debug, userConfig.getIsDebug());
        sharedEditor.putString("com.qc.Action_DeviceName", userConfig.getDeviceName());
        sharedEditor.putString("com.qc.Action_Device_Address", userConfig.getDeviceAddress());
        sharedEditor.putString(Action_Hw_version, userConfig.getHwVersion());
        sharedEditor.putString(Action_fm_version, userConfig.getFmVersion());
        sharedEditor.putString(Action_battery, userConfig.getBattery());
        sharedEditor.putString(Action_Last_Device, userConfig.getLastDeviceAddress());
        sharedEditor.putString(Action_HealthyModel, userConfig.getHealthyModel());
        sharedEditor.putString(Action_Device_Name_No_Clear, userConfig.getDeviceNameNoClear());
        sharedEditor.putString(Action_Device_Address_No_Clear, userConfig.getDeviceAddressNoClear());
        sharedEditor.putBoolean(Action_Login_Status, userConfig.getLoginStatus());
        sharedEditor.putString(Action_UserToken, userConfig.getUserToken());
        sharedEditor.putString(Action_UserEmail, userConfig.getUserEmail());
        sharedEditor.putString(Action_UserPwd, userConfig.getUserPwd());
        sharedEditor.putLong(Action_UID, userConfig.getUid());
        sharedEditor.putBoolean(Action_Metric, userConfig.getMetric());
        sharedEditor.putBoolean(Action_MenstruationSetting, userConfig.getMenstruationSetting());
        sharedEditor.putBoolean(Action_Call_Push, userConfig.getCallPushEnable());
        sharedEditor.putBoolean(Action_Sms_Push, userConfig.getSmsPushEnable());
        sharedEditor.putLong(Action_WakeUp_Time, userConfig.getWakeTime());
        sharedEditor.putBoolean(Action_MessagePush, userConfig.getMessagePushEnable());
        sharedEditor.putInt(Action_Weather_LastTime, userConfig.getWeatherLastTime());
        sharedEditor.putInt(Action_Weather_ToDevice_LastTime, userConfig.getWeatherToDeviceLastTime());
        sharedEditor.putString(Action_Weather_Info, userConfig.getWeatherInfo());
        sharedEditor.putBoolean(Action_Permission_Desc, userConfig.getPermissionDescFlag());
        sharedEditor.putBoolean(Action_Gps_Warming, userConfig.getGpsWarmingDialog());
        sharedEditor.putString(Action_Language_Curr, userConfig.getLanguageCurr());
        sharedEditor.putInt(Action_Skin_Curr, userConfig.getSkinType());
        sharedEditor.putLong(Action_lastSyncFromServerTime, userConfig.getLastSyncFromServerTime());
        sharedEditor.putString(Action_OneKeySupport, userConfig.getOneKeySupport());
        sharedEditor.putBoolean(Action_firstUser, userConfig.getFirstUse());
        sharedEditor.putLong(Action_lastSyncTodaySteps, userConfig.getLastSyncTodaySteps());
        sharedEditor.putLong(Action_watchFaceMarketVersion, userConfig.getWatchFaceMarketVersion());
        sharedEditor.putLong(Action_lastCollectionTime, userConfig.getLastCollectionTime());
        sharedEditor.putLong(Action_gpsPermission, userConfig.getGpsPermission());
        sharedEditor.putBoolean(Action_warmingNotification, userConfig.getWarmingNotification());
        sharedEditor.putBoolean(Action_warmingBatteryWhite, userConfig.getWarmingBatteryWhite());
        sharedEditor.putBoolean(Action_warmingAutoStart, userConfig.getWarmingAutoStart());
        sharedEditor.putBoolean(Action_warmingLockApp, userConfig.getWarmingLock());
        sharedEditor.putBoolean(Action_warmingBatteryAllow, userConfig.getWarmingBatteryAllow());
        sharedEditor.putLong(Action_UserPhotoAction, userConfig.getLastUserPhotoModifyTime());
        sharedEditor.putBoolean(Action_GoogleFit, userConfig.getGoogleFit());
        sharedEditor.putBoolean(Action_newSleepProtocol, userConfig.getNewSleepProtocol());
        sharedEditor.putBoolean(Action_temperature, userConfig.getTemperature());
        sharedEditor.putString(Action_google_fit_last_info, userConfig.getGoogleFitLastInfo());
        sharedEditor.putInt(Action_maxWatchFace, userConfig.getMaxWatchFace());
        sharedEditor.putBoolean(Action_otherSoftwarePush, userConfig.getOtherSoftwarePush());
        sharedEditor.putBoolean(Action_SupportContact, userConfig.getSupportContact());
        sharedEditor.putLong(Action_lastTenMinSyncTime, userConfig.getLastTenMinSyncTime());
        sharedEditor.putInt(Action_serverMarketSize, userConfig.getServerMarketSize());
        sharedEditor.putString(Action_Classic_Bluetooth_Mac, userConfig.getClassicBluetoothMac());
        sharedEditor.putString(Action_DeviceActionList, userConfig.getDeviceFunctionList());
        sharedEditor.putInt(Action_IndexApiUpdateTme, userConfig.getIndexApiUpdateTime());
        sharedEditor.putString(Action_Skus, userConfig.getSkusGoogle());
        sharedEditor.putInt(Action_LastLocation, userConfig.getLastLocationTime());
        sharedEditor.putInt(Action_MaxContacts, userConfig.getMaxContacts());
        sharedEditor.putBoolean(Action_WatchFaceApiFlag, userConfig.getWatchFaceApiFlag());
        sharedEditor.putBoolean(Action_MusicSupport, userConfig.getMusicSupport());
        sharedEditor.putBoolean(Action_RtkMcuSupport, userConfig.getRtkMcuSupport());
        sharedEditor.putBoolean(Action_Action_Ebook, userConfig.getEbookSupport());
        sharedEditor.putBoolean(Action_Support_WeChat, userConfig.getWechatSupport());
        sharedEditor.putBoolean(Action_China_App, userConfig.getChinaApp());
        sharedEditor.putBoolean(Action_ManualDND, userConfig.getManualDND());
        sharedEditor.putBoolean(Action_devTest, userConfig.getDevelopment());
        sharedEditor.putBoolean(Action_BloodSugarSupport, userConfig.getBloodSugarSupport());
        sharedEditor.putBoolean(Action_LyricsSupport, userConfig.getLyricsSupport());
        sharedEditor.putBoolean(Action_AlbumSupport, userConfig.getAlbumSupport());
        sharedEditor.putBoolean(Action_GPSSupport, userConfig.getGpsSupport());
        sharedEditor.putInt(Action_Travel_Mode, userConfig.getTravelModel());
        sharedEditor.putBoolean(Action_JieLiMusic, userConfig.getJieLiMusic());
        sharedEditor.putLong(Action_GpsLocationTime, userConfig.getGpsLocationTime());
        sharedEditor.putInt(Action_MessagePushDeviceSupport, userConfig.getMessagePushSupport());
        sharedEditor.putBoolean(Action_deviceAvatarSupport, userConfig.getDeviceAvatarSupport());
        sharedEditor.putBoolean(Action_deviceBatteryLow, userConfig.getBatteryLow());
        sharedEditor.putBoolean(Action_heartRateIntervalSupport, userConfig.getHeartRateInterval());
        sharedEditor.commit();
    }

    public final void clear(com.qcwireless.qcwatch.base.pref.UserConfig userConfig) {
        kotlin.jvm.internal.Intrinsics.checkNotNullParameter(userConfig, "userConfig");
        android.content.SharedPreferences.Editor sharedEditor = com.qcwireless.qcwatch.base.pref.PreUtil.getSharedEditor(PREFERENCE_FILE_NAME, userConfig.getContext());
        sharedEditor.clear();
        sharedEditor.commit();
    }
}
