#!/usr/bin/env python3
"""
COLMI R12 (RTL8762C) OTA Image Patcher / Generator

Generates a valid OTA update file for the COLMI R12 smart ring by:
  1. Taking a donor OTA file (for the proprietary header fields)
  2. Replacing the firmware payload with a patched version
  3. Recalculating the header checksum

OTA file format (1104-byte header + raw firmware):
  +0x000 [4]   magic            Build signature (0x81bdc3e5 for RT11CR)
  +0x004 [4]   payload_size     Size from +0x50 to EOF (= 0x400 + fw_size)
  +0x008 [4]   payload_size2    Duplicate of payload_size
  +0x00C [4]   byte_sum         Additive byte sum of data from +0x50 to EOF
  +0x010 [32]  version_str      e.g. "RT11CR_1.00.08_250514"
  +0x030 [32]  platform_str     e.g. "RT11CR_V1.0"
  --- Bee2 Image Descriptor (0x400 bytes) ---
  +0x050 [4]   ctrl_header      Image type/flags (0x0981000c)
  +0x054 [4]   git_version      Build version counter
  +0x058 [4]   fw_size          Raw firmware payload size
  +0x05C [16]  img_hash_lo      Proprietary hash (first 16 bytes)
  +0x06C [4]   load_addr        Flash load address (0x00826400)
  +0x070 [4]   img_addr         Same as load_addr
  +0x078 [4]   exe_addr         Execution/base address (0x00826000)
  +0x0B0 [4]   app_hdr_magic    App header magic (0x00001041)
  +0x0B4 [4]   app_hdr_ver      App header version
  +0x0B8 [8]   sdk_marker       "sdk#####"
  +0x1C4 [32]  img_hash_hi      Proprietary hash (remaining 32 bytes)
  +0x228 [8]   unknown_field    Unknown (possibly CRC or auth tag)
  +0x330 [16]  padding_ff_1     0xFF padding (reserved)
  +0x440 [16]  padding_ff_2     0xFF padding (reserved)
  --- Raw Firmware ---
  +0x450 [N]   firmware         Raw firmware binary

The proprietary hashes at +0x5C and +0x1C4 are generated by the Bee2 SDK's
prepend_header tool using an unknown algorithm. When patching, we preserve
these from the donor OTA file. If the ROM bootloader validates them, the OTA
will fail safely (dual-bank architecture preserves the old firmware).

The QRing app's DFU protocol (DfuHandle.java) additionally computes:
  - CRC16-MODBUS of the entire OTA file
  - 16-bit additive byte sum of the entire OTA file
These are sent during the "init" step and are computed at runtime by the app,
so they are always correct for whatever file you give it.
"""

import struct
import argparse
import sys
import os


HEADER_SIZE = 0x450  # 1104 bytes
IMG_DESC_OFFSET = 0x50
IMG_DESC_SIZE = 0x400
BYTE_SUM_OFFSET = 0x0C
PAYLOAD_SIZE_OFFSET = 0x04
PAYLOAD_SIZE2_OFFSET = 0x08
FW_SIZE_OFFSET = 0x58
MAGIC_OFFSET = 0x00
VERSION_OFFSET = 0x10
PLATFORM_OFFSET = 0x30


def compute_byte_sum(data: bytes) -> int:
    """Compute the additive byte sum used in the OTA header at +0x0C."""
    return sum(data) & 0xFFFFFFFF


def read_file(path: str) -> bytes:
    with open(path, 'rb') as f:
        return f.read()


def write_file(path: str, data: bytes):
    with open(path, 'wb') as f:
        f.write(data)


def parse_ota(ota: bytes) -> dict:
    """Parse an OTA file and return its components."""
    if len(ota) < HEADER_SIZE + 16:
        raise ValueError(f"OTA file too small: {len(ota)} bytes (minimum {HEADER_SIZE + 16})")

    header = ota[:HEADER_SIZE]
    firmware = ota[HEADER_SIZE:]

    magic = struct.unpack_from('<I', header, MAGIC_OFFSET)[0]
    payload_size = struct.unpack_from('<I', header, PAYLOAD_SIZE_OFFSET)[0]
    byte_sum_stored = struct.unpack_from('<I', header, BYTE_SUM_OFFSET)[0]
    fw_size = struct.unpack_from('<I', header, FW_SIZE_OFFSET)[0]
    version_str = header[VERSION_OFFSET:VERSION_OFFSET + 32].split(b'\x00')[0].decode('ascii', errors='replace')
    platform_str = header[PLATFORM_OFFSET:PLATFORM_OFFSET + 32].split(b'\x00')[0].decode('ascii', errors='replace')
    load_addr = struct.unpack_from('<I', header, 0x6C)[0]
    exe_addr = struct.unpack_from('<I', header, 0x78)[0]

    # Verify
    expected_payload = IMG_DESC_SIZE + len(firmware)
    byte_sum_computed = compute_byte_sum(ota[IMG_DESC_OFFSET:])

    return {
        'header': bytearray(header),
        'firmware': firmware,
        'magic': magic,
        'payload_size': payload_size,
        'byte_sum_stored': byte_sum_stored,
        'byte_sum_computed': byte_sum_computed,
        'byte_sum_ok': byte_sum_stored == byte_sum_computed,
        'fw_size': fw_size,
        'fw_size_ok': fw_size == len(firmware),
        'payload_size_ok': payload_size == expected_payload,
        'version_str': version_str,
        'platform_str': platform_str,
        'load_addr': load_addr,
        'exe_addr': exe_addr,
    }


def build_ota(donor_header: bytearray, firmware: bytes) -> bytes:
    """
    Build a new OTA file using a donor header and replacement firmware.
    
    The donor header provides all proprietary fields (hashes, signatures).
    Size-dependent fields and the checksum are recalculated.
    """
    header = bytearray(donor_header)

    # Update firmware size
    struct.pack_into('<I', header, FW_SIZE_OFFSET, len(firmware))

    # Update payload size (0x400 image descriptor + firmware)
    payload_size = IMG_DESC_SIZE + len(firmware)
    struct.pack_into('<I', header, PAYLOAD_SIZE_OFFSET, payload_size)
    struct.pack_into('<I', header, PAYLOAD_SIZE2_OFFSET, payload_size)

    # Build the complete file (header + firmware)
    ota = bytes(header) + firmware

    # Compute and store the byte sum from +0x50 to end
    byte_sum = compute_byte_sum(ota[IMG_DESC_OFFSET:])
    struct.pack_into('<I', header, BYTE_SUM_OFFSET, byte_sum)

    # Rebuild with corrected checksum
    ota = bytes(header) + firmware

    return ota


def apply_patches(firmware: bytearray, patches: list[tuple[int, bytes]], base_addr: int = 0) -> bytearray:
    """
    Apply binary patches to firmware.
    
    patches: list of (address, bytes) tuples.
             If base_addr > 0, addresses are treated as absolute and adjusted.
    """
    fw = bytearray(firmware)
    for addr, data in patches:
        offset = addr - base_addr if base_addr > 0 else addr
        if offset < 0 or offset + len(data) > len(fw):
            raise ValueError(f"Patch at 0x{addr:08x} (offset 0x{offset:x}) out of range "
                           f"(firmware size: 0x{len(fw):x})")
        fw[offset:offset + len(data)] = data
    return fw


def cmd_info(args):
    """Display OTA file information."""
    ota = read_file(args.ota_file)
    info = parse_ota(ota)

    print(f"File:          {args.ota_file}")
    print(f"Total size:    {len(ota)} bytes (0x{len(ota):x})")
    print(f"Header:        {HEADER_SIZE} bytes")
    print(f"Firmware:      {len(info['firmware'])} bytes")
    print(f"")
    print(f"Magic:         0x{info['magic']:08x}")
    print(f"Version:       {info['version_str']}")
    print(f"Platform:      {info['platform_str']}")
    print(f"Payload size:  0x{info['payload_size']:08x}  {'✓' if info['payload_size_ok'] else '✗ MISMATCH'}")
    print(f"FW size field: 0x{info['fw_size']:08x}  {'✓' if info['fw_size_ok'] else '✗ MISMATCH'}")
    print(f"Byte sum:      0x{info['byte_sum_stored']:08x}  {'✓' if info['byte_sum_ok'] else '✗ MISMATCH (computed: 0x' + format(info['byte_sum_computed'], '08x') + ')'}")
    print(f"Load addr:     0x{info['load_addr']:08x}")
    print(f"Exe addr:      0x{info['exe_addr']:08x}")
    print(f"")
    print(f"Hash (0x5C):   {info['header'][0x5C:0x6C].hex()}")
    print(f"Hash (0x1C4):  {info['header'][0x1C4:0x1E4].hex()}")
    print(f"Unk  (0x228):  {info['header'][0x228:0x230].hex()}")


def cmd_patch(args):
    """Patch firmware in an OTA file."""
    donor_ota = read_file(args.donor)
    donor_info = parse_ota(donor_ota)

    if not donor_info['byte_sum_ok']:
        print(f"WARNING: donor OTA checksum mismatch", file=sys.stderr)
    if not donor_info['fw_size_ok']:
        print(f"WARNING: donor OTA firmware size mismatch", file=sys.stderr)

    # Load the firmware to inject
    if args.firmware:
        firmware = bytearray(read_file(args.firmware))
        print(f"Firmware from: {args.firmware} ({len(firmware)} bytes)")
    else:
        firmware = bytearray(donor_info['firmware'])
        print(f"Firmware from: donor ({len(firmware)} bytes)")

    # Apply hex patches from command line
    if args.hex_patch:
        for patch_spec in args.hex_patch:
            addr_str, hex_str = patch_spec.split(':', 1)
            addr = int(addr_str, 16)
            data = bytes.fromhex(hex_str.replace(' ', ''))
            print(f"Hex patch: {len(data)} bytes at 0x{addr:05x}")
            firmware = apply_patches(firmware, [(addr, data)])

    # Apply patch file (format: one "offset:hexbytes" per line)
    if args.patch_file:
        with open(args.patch_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                addr_str, hex_str = line.split(':', 1)
                addr = int(addr_str, 16)
                data = bytes.fromhex(hex_str.replace(' ', ''))
                print(f"File patch: {len(data)} bytes at 0x{addr:05x}")
                firmware = apply_patches(firmware, [(addr, data)])

    # Build the OTA
    ota = build_ota(donor_info['header'], bytes(firmware))

    # Verify
    verify_info = parse_ota(ota)
    assert verify_info['byte_sum_ok'], "Checksum verification failed!"
    assert verify_info['fw_size_ok'], "FW size verification failed!"

    write_file(args.output, ota)
    print(f"")
    print(f"Output:        {args.output}")
    print(f"Size:          {len(ota)} bytes")
    print(f"Byte sum:      0x{verify_info['byte_sum_stored']:08x}")
    print(f"FW size:       {len(firmware)} bytes")

    if donor_info['byte_sum_stored'] != verify_info['byte_sum_stored']:
        print(f"Checksum changed: 0x{donor_info['byte_sum_stored']:08x} → 0x{verify_info['byte_sum_stored']:08x}")


def cmd_extract(args):
    """Extract raw firmware from an OTA file."""
    ota = read_file(args.ota_file)
    info = parse_ota(ota)
    write_file(args.output, info['firmware'])
    print(f"Extracted {len(info['firmware'])} bytes to {args.output}")


def main():
    parser = argparse.ArgumentParser(
        description='COLMI R12 (RTL8762C) OTA image patcher',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Show OTA file info
  %(prog)s info RT11CR_1_00_08_250514.bin

  # Extract raw firmware from OTA
  %(prog)s extract RT11CR_1_00_08_250514.bin -o firmware.bin

  # Patch firmware at specific offsets (file offsets, not flash addresses)
  %(prog)s patch RT11CR_1_00_08_250514.bin -o patched.bin \\
      -x 055ea:1cf032bd \\
      -x 22052:4178fe2905d010b592b000490847efb5...

  # Patch with a pre-modified firmware binary
  %(prog)s patch RT11CR_1_00_08_250514.bin -o patched.bin \\
      -f my_modified_firmware.bin

  # Patch using a patch file
  %(prog)s patch RT11CR_1_00_08_250514.bin -o patched.bin -p patches.txt
  # patches.txt format (one per line, # comments allowed):
  #   055ea:1cf032bd
  #   22052:4178fe29...
""")

    sub = parser.add_subparsers(dest='command', required=True)

    # info
    p_info = sub.add_parser('info', help='Display OTA file information')
    p_info.add_argument('ota_file', help='OTA file to inspect')

    # extract
    p_extract = sub.add_parser('extract', help='Extract raw firmware from OTA')
    p_extract.add_argument('ota_file', help='OTA file to extract from')
    p_extract.add_argument('-o', '--output', required=True, help='Output firmware file')

    # patch
    p_patch = sub.add_parser('patch', help='Build patched OTA file')
    p_patch.add_argument('donor', help='Donor OTA file (provides header template)')
    p_patch.add_argument('-o', '--output', required=True, help='Output OTA file')
    p_patch.add_argument('-f', '--firmware', help='Replacement firmware binary (default: use donor firmware)')
    p_patch.add_argument('-x', '--hex-patch', action='append', metavar='OFFSET:HEXBYTES',
                        help='Hex patch as offset:hexbytes (file offset, not flash addr)')
    p_patch.add_argument('-p', '--patch-file', help='File containing patches (offset:hexbytes per line)')

    args = parser.parse_args()

    if args.command == 'info':
        cmd_info(args)
    elif args.command == 'extract':
        cmd_extract(args)
    elif args.command == 'patch':
        cmd_patch(args)


if __name__ == '__main__':
    main()
